version: '3.8'

services:
  backend:
    build: ./backend
    container_name: smart-cashier-platform-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - smart-cashier-network

  frontend:
    build: ./frontend
    container_name: smart-cashier-platform-frontend
    ports:
      - "5173:5173"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - smart-cashier-network

  mongo:
    image: mongo:latest
    container_name: smart-cashier-platform-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - smart-cashier-network

volumes:
  mongo-data:

networks:
  smart-cashier-network:
    driver: bridge
